language: java

jdk:
  - oraclejdk8

os:
  - linux

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)